# Ctrl + B works fine; I use tmux on my server so I don't want to get confused by using two different binds.

#unbind C-b
#set -g prefix C-Space
#bind C-Space send-prefix

set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'alacritty:RGB'

set -g mouse on

bind -n M-H previous-window
bind -n M-L next-window

bind-key -r H run-shell "~/.local/bin/tmux-sessionizer ~/.config/nvim"
bind-key -r T run-shell "~/.local/bin/tmux-sessionizer ~/Vault"
#bind-key -r N run-shell "~/.local/bin/tmux-sessionizer ~/personal/harpoon"
#bind-key -r S run-shell "~/.local/bin/tmux-sessionizer ~/personal/developer-productivity"
